source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'JSPatchSwift' do
    pod 'Alamofire', '~> 3.4'
    pod 'SwiftyJSON', '~> 2.3.1'
    pod 'RxSwift',    '~> 2.0'
    pod 'RxCocoa',    '~> 2.0'
    pod 'RxDataSources', '~> 0.7'
    pod 'IQKeyboardManagerSwift', '4.0.3'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'RealmSwift'
    pod 'MJRefresh'
    pod 'Kingfisher', '~> 2.4'
    pod 'JSPatch'
end
